# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
