# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170711_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='brochure_link',
            field=models.CharField(default='NIL', max_length=300),
        ),
        migrations.AddField(
            model_name='events',
            name='event_photo',
            field=models.CharField(default='NIL', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='note',
            field=models.CharField(default='NIL', max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='objective',
            field=models.CharField(default='NIL', max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='perks',
            field=models.CharField(default='NIL', max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='registration_fee_ieee',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='events',
            name='registration_fee_non_ieee',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='events',
            name='registration_link',
            field=models.CharField(default='NIL', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='scope',
            field=models.CharField(default='NIL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='coord',
            field=models.CharField(default='NIL', max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='no_of_participants',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='events',
            name='speakers',
            field=models.CharField(default='NIL', max_length=500),
        ),
    ]
