# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170812_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='registration_link',
            field=models.CharField(default='NIL', max_length=1000),
        ),
    ]
