# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='NIL', max_length=500),
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo_number',
            field=models.IntegerField(default=-1, max_length=500),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='NIL', max_length=100),
        ),
    ]
