# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170812_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo_number',
            field=models.IntegerField(default=-1),
        ),
    ]
