# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170812_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='schedule_link',
            field=models.CharField(default='NIL', max_length=300),
        ),
    ]
