# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_events_schedule_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='note',
            field=models.CharField(default='NIL', max_length=10000),
        ),
    ]
